# Generated by Django 4.1.4 on 2023-02-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_createmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmodel',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='createmodel',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
