# Generated by Django 4.1.4 on 2023-02-17 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_alter_createmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 15, 12, 6, 355425), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='createmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
